# Generated by Django 2.2.24 on 2021-12-06 17:52

import datetime

from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ("authnapp", "0006_auto_20211202_0852"),
    ]

    operations = [
        migrations.AlterField(
            model_name="shopuser",
            name="activation_key_expires",
            field=models.DateTimeField(
                default=datetime.datetime(2021, 12, 8, 17, 52, 14, 637817, tzinfo=utc),
                verbose_name="актуальность ключа",
            ),
        ),
    ]
